env:
  - CGO_ENABLED=0

before:
  hooks:
    - make test

builds:
  - id: build
    targets:
      - darwin_amd64
      - freebsd_386
      - freebsd_amd64
      - freebsd_arm
      - linux_386
      - linux_amd64
      - linux_arm
      - openbsd_386
      - openbsd_amd64
      - solaris_amd64
      - windows_386
      - windows_amd64

# When draft=true, the github pipeline is skipped, so we can't use that feature.
release:
  github:
    owner: hashicorp
    name: terraform-provider-alpha
  prerelease: true
  draft: false

archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false
    # only add the binary to the archive
    files:
      - none*

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

changelog:
  skip: true
