name: Check examples
on:
  push:
    paths:
    - 'examples/**'
    - '**.go'
  pull_request:
    branches:
    - master
    paths:
    - 'examples/**'
    - '**.go'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Read go-version
      id: go-version
      uses: juliangruber/read-file-action@v1
      with:
        path: ./go-version
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ steps.go-version.outputs.content }}
    - uses: engineerd/setup-kind@v0.3.0
    - name: Check examples run
      run: ./scripts/check_examples.sh
      env:
        TERM: xterm-256color
      shell: bash
